import type { Command } from "commander";
import { lightColors } from "../../utils/colors.js";

export const registerPrivacyCommand = (program: Command): void => {
  program
    .command("privacy")
    .description("Show privacy settings and data handling information")
    .action(async (): Promise<void> => {
      console.log(`${lightColors.blue("🔒 Commit-X Privacy Information:\n")}

${lightColors.yellow("Data Sent to AI:")}
  • File paths (sanitized to remove usernames)
  • Code changes (up to 3000 characters per file)
  • File metadata (additions/deletions counts)
  • File status (new/modified/deleted/renamed)

${lightColors.yellow("Data NOT Sent to AI:")}
  • API keys or authentication tokens
  • Personal information (names, emails)
  • System information (OS, hardware)
  • Repository metadata (URLs, branch names)

${lightColors.yellow("Privacy Protections:")}
  • Sensitive files are automatically skipped before AI call
  • File paths are sanitized to remove usernames
  • Potential secrets are redacted from content
  • Content is limited per file and total request size is capped

${lightColors.yellow("Auto-skipped File Types:")}
  • .env*, *.key, *.pem, *.p12, *.pfx, *.p8 files
  • Files in secrets/, keys/, credentials/ directories
  • Files containing API keys, passwords, or tokens

${lightColors.yellow("Deterministic (No AI) File Types:")}
  • Lock files (package-lock.json, yarn.lock, pnpm-lock.yaml, etc.)
  • Docs (README, LICENSE, CHANGELOG, CONTRIBUTING)
  • Minified assets (*.min.js, *.min.css, *.map)
  • Generated files (*.generated.*, *.g.ts, *.pb.*)
  • Build artifacts (dist/, build/, out/, .next/, target/)

${lightColors.yellow("Commit Message Cache:")}
  • Fresh messages are generated by default (no cache read/write)
  • Use --use-cached to opt in to cached results

${lightColors.gray("For more information, visit: https://github.com/sojanvarghese/commit-x#privacy")}`);
    });
};
